### ISSUE TITLE
Can we add Mate-Terminal ?

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/eos-quickstart#1]
Seems Mate Terminal (mate-terminal) is not supported by terminal search and it will use xterm if installed on Mate installs.. but if none of the supported Terminals is installed it will simply do nothing on mate when click on install button.

**Comment by ringo32** [comment]
qterminal is also not supported ^^

**Comment by NovaViper** [comment]
Can Kitty terminal also be added?

**Comment by killajoe** [comment]
from my pov i think terminals from the default installable Desktops should be in and supported.

**Comment by dalto8** [comment]
Implemented with https://github.com/endeavouros-team/eos-quickstart/commit/cc1ab9e074e1173589a37034184003546eedf2f4
