### ISSUE TITLE
qpdfview decapriated replace with xpdf ?

### ISSUE THREAD

**Issue by ringo32** [endeavouros-team/eos-quickstart#2]
qpdfview is no more in repo : rip

other lightweight qt5 is xpdf is nice :)

also mupdf would be nice as a lightweight option.

**Comment by killajoe** [comment]
![2023-02-25_12-09](https://user-images.githubusercontent.com/16797647/221353634-cdcaeb50-fab7-4808-81ba-510c01260227.png)
